# Generated by Django 3.1.3 on 2020-11-22 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201122_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 22, 22, 11, 10, 832126)),
        ),
    ]
